server:
  port: 8880
  contextPath: /uaa

spring:
  application:
    name: auth-service
  ldap:
    embedded:
      base-dn: "dc=sidenis,dc=com"
      port: 9321
      ldif: classpath:/test-server.ldif

security:
  oauth:
    signing: token123

test:
  security:
    user:
      name: ben
      password: benspassword