server:
  port: 8010
  contextPath: /uaa

spring:
  application:
    name: auth-service
  ldap:
    embedded:
      ldif: classpath:/test-server.ldif

security:
  oauth:
    signing: token123
  user:
    password: pass123

